[SHIPA-1234] use Recreate Deployment strategy for Shipa API
shipa-corp/helm-chart pull request #162
Opened 2021-04-26 11:49 UTC by itsksaurabh

# Description

- Use `Recreate Deployment strategy` for Shipa API termination as recommended when performing Migrations
- Inform users during installation about downtime

https://shipaio.atlassian.net/browse/SHIPA-1234

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (documentation addition or typo, file relocation)

## Final Checklist:

- [ ] I followed standard [GitHub flow](https://guides.github.com/introduction/flow/) guidelines
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

## Additional Information (omit if empty)

Please include anything else relevant to this PR that may be useful to know.

2021-04-28 11:19 UTC, aleksej-paschenko approved these changes

2021-04-29 18:34 UTC, murphybytes requested changes

2021-04-29 18:34 UTC, murphybytes commented on README.md
> +> ⚠️ NOTE: Shipa installation/Upgrade takes time and downtime to perform DB migration if needed.
I would suggest the following change.  
`NOTE: Installing or upgrading Shipa may require downtime in order to perform database migrations.`

2021-04-29 18:34 UTC, murphybytes commented on templates/NOTES.txt
> +    *** PLEASE BE PATIENT: Shipa installation/Upgrade takes time and downtime to perform DB migration if needed. ***
`installation/Upgrade` upper case `Upgrade` is grammatically incorrect as it is not a proper noun and does not start a sentence. `time and downtime` seems a little redundant.  Technically I think it's correct but it doesn't read well.  Tacking the `if needed` is using passive voice. Phrase technical documentation using active voice. https://www.grammarly.com/blog/passive-voice/?gclid=Cj0KCQjwsqmEBhDiARIsANV8H3biNn5DFXTjY7jMYAajgHJPCccWMKh5w0hNuI9JXaF4G-HRX0W-mKoaAnz3EALw_wcB&gclsrc=aw.ds

2021-04-29 18:40 UTC, itsksaurabh commented on templates/NOTES.txt
> +    *** PLEASE BE PATIENT: Shipa installation/Upgrade takes time and downtime to perform DB migration if needed. ***
Thank @murphybytes for the suggestions. I am changing both the messages accordingly.

2021-04-29 18:48 UTC, murphybytes approved these changes

2021-04-29 18:50 UTC, merged