[Shipa-763] Make shipa default resource names consistent
shipa-corp/helm-chart pull request #87
Opened 2020-12-03 10:44 UTC by itsksaurabh

# Description

Fixes [SHIPA-763](https://shipaio.atlassian.net/browse/SHIPA-763)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (documentation addition or typo, file relocation)

## Final Checklist:

- [ ] I followed standard [GitHub flow](https://guides.github.com/introduction/flow/) guidelines
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

## Additional Information (omit if empty)

Please include anything else relevant to this PR that may be useful to know.

2020-12-04 10:41 UTC, aleksej-paschenko requested changes
there is "shipaCore" section in values.yaml to configure shipa-core cluster
should we rename it to "shipaCluster"?

2020-12-04 10:41 UTC, aleksej-paschenko commented on values.yaml
> +  platformImageTag: v1.2
that is from another commit

2020-12-04 10:41 UTC, aleksej-paschenko commented on .github/pull_request_template.md
> +
from another commit

2020-12-04 10:41 UTC, aleksej-paschenko commented on scripts/common.sh
> +          external_ip=$(kubectl get svc $SERVICE_NAME --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")
please remove this change from the PR

2020-12-04 10:53 UTC, itsksaurabh commented
All those extra commits came from rebasing the branch. The branch was initially created using master but rebased it to dev after your suggestion yesterday. fixing it now.

2020-12-04 15:44 UTC, aleksej-paschenko requested changes

2020-12-04 15:44 UTC, aleksej-paschenko commented on templates/shipa-api-configmap.yaml
> +      platformImageTag: {{ .Values.shipaApi.platformImageTag }}
`Values.platforms.defaultPlatformImageTag`?

2020-12-04 15:44 UTC, aleksej-paschenko commented on scripts/init-job.sh
> +  $SHIPA_CLIENT cluster-add shipa-cluster --pool=shipa-pool \
we are renaming `shipa-core`  to `shipa-cluster` and there is `shipaCore` section in values.yaml. Should we rename it too for consistency?

2020-12-04 15:44 UTC, aleksej-paschenko commented on templates/shipa-org-configmap.yaml
> +  name: {{ template "shipa.fullname" . }}-org-config
could we have a more suitable name? it contains only org id now but  we will definitely add other values

2020-12-04 16:04 UTC, itsksaurabh commented on templates/shipa-api-configmap.yaml
> +      platformImageTag: {{ .Values.shipaApi.platformImageTag }}
I interchanged their position that is why It is appearing here. not coming from any other commit.

2020-12-04 16:06 UTC, itsksaurabh commented on templates/shipa-org-configmap.yaml
> +  name: {{ template "shipa.fullname" . }}-org-config
how about `{{ template "shipa.fullname" . }}-default-organization-config` ?

2020-12-07 10:45 UTC, aleksej-paschenko requested changes

2020-12-07 10:45 UTC, aleksej-paschenko commented on templates/shipa-org-configmap.yaml
> +  name: {{ template "shipa.fullname" . }}-default-organization-config
let's have a more general name for this config, currently, there is  an organization, but later we will add other things there

2020-12-07 10:45 UTC, aleksej-paschenko commented on templates/shipa-api-configmap.yaml
> +      platformImageTag: {{ .Values.shipaApi.platformImageTag }}
and you changed the names, check again please

2020-12-07 11:01 UTC, itsksaurabh commented on templates/shipa-org-configmap.yaml
> +  name: {{ template "shipa.fullname" . }}-default-organization-config
changed to `{{ template "shipa.fullname" . }}-defaults-configmap` as discussed

2020-12-07 12:22 UTC, koncar approved these changes

2020-12-07 12:35 UTC, aleksej-paschenko approved these changes

2020-12-07 12:50 UTC, merged